### ISSUE TITLE
il2cpp打包报错

### ISSUE THREAD

**Issue by pirumeng** [focus-creative-games/hybridclr_unity#24]
不好意思 请问一下最近打包遇到了 il2cpp redifination xxxxx的报错，il2cpp生成的ZeusCore_Attr.cpp 定义了两个同样的方法ByteBufferAllocator_t0E319F952878FBAB0B83EF60D2A5BC7C3ED5F5C8_CustomAttributesCacheGenerator_A

反编译自己的dll之后发现dll中自动生成了名字相同的变量 
private int A; 
private byte[] A;，
而我的代码在编译成dll之前是一个访问器 
public int a {get;protected set;}  
public byte[] b {get;protected set;} 并没有修改的空间，且原生il2cpp并不会造成打包报错。

请问这种情况怎么解决？（unity版本2020.3.33，hybrid_unitypackage 已经更到最新）

**Comment by pirunxi** [comment]
我们没修改il2cpp的生成的代码，所以这个问题是il2cpp自己的问题，我们无能为力。不过如果可以的话，你把提供一个可复现的工程，发给技术支持 QQ 1732047670，我们分析一下原因。
