### ISSUE TITLE
unity2021.3.1f1 WebGL平台 await UniTask报错

### ISSUE THREAD

**Issue by poetao** [focus-creative-games/hybridclr_unity#26]
Unity Editor版本: 2021.3.1f1
操作系统:  macOS Big Sur
出错的Build Target: WebGL
com.focus-creative-games.hybridclr_unity的版本号: 2.0.0
hybridclr仓库的版本号:  main 531f98365eebce5d1390175be2b41c41e217d918
il2cpp_plus仓库的版本号: 2021-main 99cd1cbbfc1f637460379e81c9a7776cd3e662ad
截图及日志文件
![image](https://user-images.githubusercontent.com/7285985/219297388-3ad067db-61c4-4056-8848-7fac4f1df28f.png)

![image](https://user-images.githubusercontent.com/7285985/219297201-2805ba18-c1fc-4db3-9f64-981e46c7dacc.png)

复现条件  await UniTask报错，clone这个仓库https://gitee.com/poetao/hybridclr_test.git 直接打包webgl平台即可
出错的c#代码位置（如果能定位出的话）
![image](https://user-images.githubusercontent.com/7285985/219297709-f75c6052-b54d-4a31-892c-2ebe65d944da.png)

**Comment by pirunxi** [comment]
你更新最新的2.0.5版本，install，再测试一下。刚刚修复这个问题。
