### ISSUE TITLE
BuildOptions' does not contain a definition for 'CleanBuildCache'

### ISSUE THREAD

**Issue by BIGWGY** [focus-creative-games/hybridclr_unity#30]
HybridCLR 的版本是 ：

![image](https://user-images.githubusercontent.com/13144389/235344383-42cc697b-8485-4e33-9f45-30b5dae6d2ff.png)

使用的Unity版本是 
![image](https://user-images.githubusercontent.com/13144389/235344375-409e6a92-e58d-46ca-900d-40100ef105f8.png)

会报标题的编译错误：
![image](https://user-images.githubusercontent.com/13144389/235344417-f2848e01-a874-4376-8643-2cd92e932b94.png)

查了一下，应该是 Unity 2021.2 才支持的：

2021.1
![image](https://user-images.githubusercontent.com/13144389/235344501-71a54273-ff4e-4a15-9638-d3f33efcd5e4.png)

2021.2
![image](https://user-images.githubusercontent.com/13144389/235344485-be0aa584-c2cd-4df6-9257-e7326745bdd4.png)

**Comment by pirunxi** [comment]
感谢，我们马上修复。
