### ISSUE TITLE
关于3.2版本 xcode工程打包给别的电脑使用的问题

### ISSUE THREAD

**Issue by kyo8598CC** [focus-creative-games/hybridclr_unity#32]
大佬你好 我看文档说是
当 com.code-philosophy.hybridclr 版本 ≥ v3.2.0
不需要任何处理，直接导出xcode工程，再打包即可。由于在build完成后才将libil2cpp源码加入xcode工程，因此只能先导出xcode，再手动或者命令行编译，试图直接Build And Run会出错。

危险
由于xcode工程里写死了 libil2cpp相关代码的路径，如果你导出xcode工程，推送到其他电脑上打包，会出现代码文件找不到的错误！

那么就意味着如果我要出xcode工程给别人的话就不能使用高版本了 还是说大佬以后会支持多种选择 可以选择还是采用原始的自己编译.a的方式

**Comment by pirunxi** [comment]
已经解决了这个问题，等下个版本。
