### ISSUE TITLE
在2022.3.11f1把Load texture data on demand选项选上后，编译会崩溃

### ISSUE THREAD

**Issue by listentowindy** [focus-creative-games/hybridclr_unity#40]
Unity Editor版本: 2022.3.11f1, 2022.3.12f1
操作系统: Windows 11 
出错的BuildTarget: Android
com.code-philosophy.hybridclr的版本号:  4.0.11, 4.0.12
复现条件:
  1）把hybridclr_trial导入到2022.3.11f1，然后把hybridclr升级到4.0.12； 把编译选项切换到android平台
  2）把ProjectSettings -> Editor的 -> Load texture data on demand选项 选上  后，运行GenerateAll步骤，unity会直接崩溃
       如果这个选项没有选上，则正常

![1D)LVTFBL4 Z7HHN93UTCG](https://github.com/focus-creative-games/hybridclr_unity/assets/6919440/01a5e09b-466f-4fb0-825c-58ed85804708)

**Comment by pirunxi** [comment]
这个我们确认了。不过这个问题只能求助Unity官方来解决。我们无法得知因何而起。猜测也许是MonoHook插件引发的。
