### ISSUE TITLE
unity 团结版本不可用

### ISSUE THREAD

**Issue by yingran-cn** [focus-creative-games/hybridclr_unity#44]

**Comment by yingran-cn** [comment]
![35bdf0e1620422ed2e08b3ac0b1e751e](https://github.com/focus-creative-games/hybridclr_unity/assets/26194916/5b1ca2c5-e727-467f-9b70-fc2f8a463b18)

**Comment by pirunxi** [comment]
社区版本不含团结引擎分支，请从https://gitee.com/ldr123/hybrid-clrtuanjie-conv获得团结引擎的分支。 详细可见 https://hybridclr.doc.code-philosophy.com/docs/basic/supportedplatformanduniyversion 文档
