### ISSUE TITLE
编译报错。找不到VisionOS

### ISSUE THREAD

**Issue by AlianBlank** [focus-creative-games/hybridclr_unity#47]
Unity 版本：2022.3.3f1 
HyBirdCLR 版本：5.4.1
![image](https://github.com/focus-creative-games/hybridclr_unity/assets/1950044/40ceb3f4-51c3-4c3a-a1c8-738e2c409e2e)

![image](https://github.com/focus-creative-games/hybridclr_unity/assets/1950044/a1defd50-71ca-48e6-9af2-53da27754e0c)

**Comment by pirunxi** [comment]
已确认，6.0.0版本已经解决了此问题
