### ISSUE TITLE
[请求功能]1. 在编辑器下面打完AOTDLL列表之后触发一个回调接口

### ISSUE THREAD

**Issue by AlianBlank** [focus-creative-games/hybridclr_unity#48]
由于默认打包的是放在HyBridCLRData 中的。如果要放在自己的资源管理中，需要手动操作一次复制。所以希望增加一个接口的实现Post 调用。方便开发者在不修改源码的情况下自动调用自定义的讲aot 代码dll 复制到自己的资源管理中.

**Comment by pirunxi** [comment]
你在打包完成后自己去aot目录复制即可，不需要什么回调。
