### ISSUE TITLE
Assembly.Load使用符号文件在Android win报错

### ISSUE THREAD

**Issue by absences** [focus-creative-games/hybridclr_unity#50]
![image](https://github.com/user-attachments/assets/407574b6-67de-4f83-a733-884b34f9431a)

复现工程，hybrid版本6.4 unity版本2021.3.41
[Unity.zip](https://github.com/user-attachments/files/16468432/Unity.zip)

**Comment by pirunxi** [comment]
感谢，我们复查一下。 另外有bug去hybridclr仓库提， 发在这儿不能及时看到

**Comment by pirunxi** [comment]
只支持portable pdb格式。 你要确保你们项目生成的pdb跟Unity生成的格式是一样的。一个校验方式是 用记事本打开pdb文件，确保它的头部跟unity生成的pdb文件的头部是一样的。
