### ISSUE TITLE
[报错].在Unity2021.3.13f1 webgl中构建AOT DLL 报错

### ISSUE THREAD

**Issue by AlianBlank** [focus-creative-games/hybridclr_unity#51]
搭配微信小游戏SDK的时候出现.

Hybrid CLR为6.6.0 和6.7.1 均出现报错.

以下为报错日志

Building HybridCLRData\StrippedAOTDllsTempProj\WebGL\index.html failed with output:

D:\UnityHub\Unity2021.3.13f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Preprocess.js:57
    throw "Preprocessor error \"" + e + "\" occured in file \"" + locals.inputPath + "\" at line " + (index + 1) + " when evaluating expression \"" + line + "\"";
    ^
Preprocessor error "ReferenceError: SHOW_DIAGNOSTICS is not defined" occured in file "D:/GitHubWorks/BBQProject/Unity/Assets/WebGLTemplates/WXTemplate2022/index.html" at line 17 when evaluating expression "#if SHOW_DIAGNOSTICS"
(Use `node --trace-uncaught ...` to show where the exception was thrown)
0x00007ff68a829f0d (Unity) StackWalker::GetCurrentCallstack
0x00007ff68a830be9 (Unity) StackWalker::ShowCallstack
0x00007ff68b797a83 (Unity) GetStacktrace
0x00007ff68be362fd (Unity) DebugStringToFile
0x00007ff6898ea172 (Unity) DebugLogHandler_CUSTOM_Internal_Log
0x000001ada0285923 (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
0x000001ada028583b (Mono JIT Code) UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
0x000001ada0285580 (Mono JIT Code) UnityEngine.Logger:Log (UnityEngine.LogType,object)
0x000001ada06c7b75 (Mono JIT Code) UnityEngine.Debug:LogError (object)
0x000001ada06c7933 (Mono JIT Code) UnityEditor.Modules.BeeBuildPostprocessor:DefaultResultProcessor (Bee.BeeDriver.NodeResult,bool,bool)
0x000001ada06c70cb (Mono JIT Code) UnityEditor.Modules.BeeBuildPostprocessor:ReportBuildResults (Bee.BeeDriver.BeeDriverResult)
0x000001ada06aaeb3 (Mono JIT Code) UnityEditor.Modules.BeeBuildPostprocessor:PostProcess (UnityEditor.Modules.BuildPostProcessArgs)
0x000001ada06a95f3 (Mono JIT Code) [BuildPostprocessor.cs:161] UnityEditor.WebGL.WebGlBuildPostprocessor:PostProcess (UnityEditor.Modules.BuildPostProcessArgs) 
0x000001ada06a91eb (Mono JIT Code) UnityEditor.Modules.DefaultBuildPostprocessor:PostProcess (UnityEditor.Modules.BuildPostProcessArgs,UnityEditor.BuildProperties&)
0x000001ada06a8a87 (Mono JIT Code) UnityEditor.PostprocessBuildPlayer:Postprocess (UnityEditor.BuildTargetGroup,UnityEditor.BuildTarget,int,string,string,string,int,int,UnityEditor.BuildOptions,UnityEditor.RuntimeClassRegistry,UnityEditor.Build.Reporting.BuildReport)
0x000001ada06a8df5 (Mono JIT Code) (wrapper runtime-invoke) <Module>:runtime_invoke_void_int_int_int_object_object_object_int_int_int_object_object (object,intptr,intptr,intptr)
0x00007ff99944fe24 (mono-2.0-bdwgc) [mini-runtime.c:3445] mono_jit_runtime_invoke 
0x00007ff99938e764 (mono-2.0-bdwgc) [object.c:3066] do_runtime_invoke 
0x00007ff99938e8fc (mono-2.0-bdwgc) [object.c:3113] mono_runtime_invoke 
0x00007ff68a74e904 (Unity) scripting_method_invoke
0x00007ff68a72e1a4 (Unity) ScriptingInvocation::Invoke
0x00007ff68c1a88e1 (Unity) CallMono
0x00007ff68c1b0b97 (Unity) PostprocessPlayer
0x00007ff68c1ab79f (Unity) DoBuildPlayer_PostBuild
0x00007ff68c1a976e (Unity) DoBuildPlayer
0x00007ff68c19d86d (Unity) BuildPlayer
0x00007ff68a0271d6 (Unity) BuildPipeline::BuildPlayerInternalNoCheck
0x00007ff689da6280 (Unity) BuildPipeline_CUSTOM_BuildPlayerInternalNoCheck
0x000001ada044e8c7 (Mono JIT Code) (wrapper managed-to-native) UnityEditor.BuildPipeline:BuildPlayerInternalNoCheck (string[],string,string,UnityEditor.BuildTargetGroup,UnityEditor.BuildTarget,int,UnityEditor.BuildOptions,string[],bool)
0x000001ada045fe3b (Mono JIT Code) UnityEditor.BuildPipeline:BuildPlayerInternal (string[],string,string,UnityEditor.BuildTargetGroup,UnityEditor.BuildTarget,int,UnityEditor.BuildOptions,string[])
0x000001ada045f74b (Mono JIT Code) UnityEditor.BuildPipeline:BuildPlayer (string[],string,string,UnityEditor.BuildTargetGroup,UnityEditor.BuildTarget,int,UnityEditor.BuildOptions,string[])
0x000001ada045f56b (Mono JIT Code) UnityEditor.BuildPipeline:BuildPlayer (UnityEditor.BuildPlayerOptions)
0x000001ada045c8a3 (Mono JIT Code) [StripAOTDllCommand.cs:144] HybridCLR.Editor.Commands.StripAOTDllCommand:GenerateStripedAOTDlls (UnityEditor.BuildTarget) 
0x000001ada03fad93 (Mono JIT Code) [PrebuildCommand.cs:32] HybridCLR.Editor.Commands.PrebuildCommand:GenerateAll () 
0x000001ad3826961d (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void (object,intptr,intptr,intptr)
0x00007ff99944fe24 (mono-2.0-bdwgc) [mini-runtime.c:3445] mono_jit_runtime_invoke 
0x00007ff99938e764 (mono-2.0-bdwgc) [object.c:3066] do_runtime_invoke 
0x00007ff99938e8fc (mono-2.0-bdwgc) [object.c:3113] mono_runtime_invoke 
0x00007ff68a74e904 (Unity) scripting_method_invoke
0x00007ff68a72e1a4 (Unity) ScriptingInvocation::Invoke
0x00007ff68a72e28e (Unity) ScriptingInvocation::InvokeChecked
0x00007ff68b56c2d1 (Unity) ScriptCommands::InvokeMenuItemWithContext
0x00007ff68b56978a (Unity) ScriptCommands::Execute
0x00007ff68b1819b0 (Unity) MenuController::ExecuteMenuItem
0x00007ff68b79ec36 (Unity) ProcessMainWindowMessages
0x00007ff68b7bf45c (Unity) ContainerWindow::ContainerWndProc
0x00007ff9e0e28211 (USER32) DispatchMessageW
0x00007ff9e0e27cd1 (USER32) DispatchMessageW
0x00007ff68b79daa3 (Unity) MainMessageLoop
0x00007ff68b7a24cb (Unity) WinMain
0x00007ff68cb434be (Unity) __scrt_common_main_seh
0x00007ff9e00326ad (KERNEL32) BaseThreadInitThunk
0x00007ff9e110aa68 (ntdll) RtlUserThreadStart

**Comment by pirunxi** [comment]
与hybridclr无关，自查
