### ISSUE TITLE
团结 HMIAndroid, Generate/AOTDlls 不复制到配置路径

### ISSUE THREAD

**Issue by Lu-Kye** [focus-creative-games/hybridclr_unity#53]
添加了下面的修改就好了。
![image](https://github.com/user-attachments/assets/8315b6bd-4234-4e29-98ff-a77e633d3f3b)

**Comment by pirunxi** [comment]
ok，非常感谢，能否提个pr给我们

**Comment by pirunxi** [comment]
我们已经完成修复了。不必提pr了，感谢。
